### ISSUE TITLE
No examples or documentation of what can be filtered / passed in config

### ISSUE THREAD

**Issue by Nightshade-tools** [casewalker/narrate-chat-mod#1]
Maybe it has been posted somewhere or there is a file that I am missing but I am unable to find information (documentation) on how to use the config file.

I know of the file in the test/ folder:
https://github.com/casewalker/narrator-configs-mod/blob/main/src/test/resources/narratorconfigsmod.json

but this is very rudimentary. I understand they are some kind of object references (chat.type.advancement.) but where can I find a full list of these things?

**Comment by casewalker** [comment]
Hello! This is the wrong mod for this issue (you are referring to the [Narrator Configs Mod](https://github.com/casewalker/narrator-configs-mod)), so I will close it now.

**Comment by Nightshade-tools** [comment]
Yes that makes sense. Sorry about my mistake!

**Comment by Nightshade-tools** [comment]
Okay I have written an issue ticket +some comments on the correct git page.
No matter what I do with the config file I can't get anything to work.
